[tool.pyright]
name = "flask"
version = "1.0.0"
description = "Basic blog app built in flask."
dependencies = [
   "flask",
   "pillow",
   "flask-sqlalchemy",
   "pyuwsgi",
   "werkzeug",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
